import { forwardRef, HTMLAttributes, PropsWithChildren } from "react";

// Autogenerated. Modify this as needed.
interface BaseProps extends PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

export interface BoxProps extends BaseProps {}

const Box = forwardRef<HTMLDivElement, BoxProps>((props, ref) => {
  return <div ref={ref} {...props} />;
});

export default Box;
