import { HTMLAttributes, PropsWithChildren } from 'react';

  // Autogenerated. Modify this as needed.
  interface BaseProps extends PropsWithChildren<HTMLAttributes<HTMLDivElement>> {}

  export interface BoxProps extends BaseProps {}

  const Box = (props: BoxProps) => {
    return <div {...props}>Box</div>;
  };

  export default Box;
  
